branches:
  only:
    - master
    - dev
sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
before_intall:
  - npm install
script: |
  (
    gulp scripts
    git_sha=$(git rev-parse HEAD)
    git_branch=$(git rev-parse --abbrev-ref HEAD)
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t kirandasika30/postman:$git_sha-$git_branch -f Dockerfile .
    docker push kirandasika30/postman:$git_sha-$git_branch
  )
notifications:
  email:
    - szd0053@tigermail.auburn.edu
  on_success: always
  on_failure: always
