branches:
  only:
    - master
    - dev
    - jwt
sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
before_intall:
  - npm install
script: |
  (
    set -exuo pipefail
    gulp scripts
    git_sha=$(git rev-parse HEAD)
    git_branch=$(git rev-parse --abbrev-ref HEAD)
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t $DOCKER_USERNAME/postman:$git_sha -t $DOCKER_USERNAME/postman:latest -f Dockerfile .
    docker push $DOCKER_USERNAME/postman:$git_sha
    docker push $DOCKER_USERNAME/postman:latest
  )
notifications:
  email:
    - szd0053@tigermail.auburn.edu
  on_success: always
  on_failure: always
